0.12.0
eldoriarpg/BloodNight pull request #120
Opened 2022-09-27 21:53 UTC by stumper66

This is a simple change that makes any rider mobs set mobType in their PDC to match their vehicle's mobType

2022-09-27 22:33 UTC, RainbowDashLabs requested changes
Thanks for implementing it. I checked the code and it seems like tagging the extension with the type will not cause any problems.

I just have two small requests for it to be merged.

2022-09-27 22:33 UTC, RainbowDashLabs commented on BloodNight-core/src/main/java/de/eldoria/bloodnight/specialmobs/SpecialMobUtil.java
> +        Optional<String> mobName = getSpecialMobType(carrier);
In that case the rider defines the mob type. The carrier is a new mob.
```suggestion
        Optional<String> mobName = getSpecialMobType(rider);
```

2022-09-27 22:33 UTC, RainbowDashLabs commented on build.gradle.kts
> +version = "0.12.0"
Increment the version to 0.11.1 since this is only a fix and not a feature addition or leave it as is and I will increment it as needed.

2022-09-28 00:07 UTC, stumper66 commented
I have made the suggested updates.

2022-09-28 08:43 UTC, RainbowDashLabs approved these changes

2022-09-28 09:42 UTC, merged